# Generated by Django 3.1.2 on 2020-10-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201019_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
