# Generated by Django 3.1.2 on 2020-10-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20201022_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('BOOKS', 'Books'), ('POTIONS', 'Potions'), ('BROOMS', 'Brooms')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
