# Generated by Django 3.1.2 on 2020-10-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20201022_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('BOOKS', 'Books'), ('BROOMS', 'Brooms'), ('DARK MAGIC', 'Dark Magic'), ('ENCHANTED ITEMS', 'Enchanted Items'), ('MISC.', 'Misc.'), ('POTIONS', 'Potions'), ('WANDS', 'Wands')], max_length=200, null=True),
        ),
    ]
