# Generated by Django 3.1.2 on 2020-10-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20201022_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bigbid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('BOOKS', 'Books'), ('BROOMS', 'Brooms'), ('DARK MAGIC', 'Dark Magic'), ('ENCHANTED ITEMS', 'Enchanted Items'), ('MISC.', 'Misc.'), ('POTIONS', 'Potions'), ('TOYS', 'Toys'), ('WANDS', 'Wands')], max_length=200, null=True),
        ),
    ]
