name: Testing # Workflow Name
on: push #On-key– when should it run?: when pushed!

jobs: # Workflows consist of jobs/tasks
  test_project: # Arbitrary name of a 1 job
    runs-on: ubuntu-latest # What virtual machine to test?: latest version of ubuntu/linux VM
    steps: # specify actions when testing
    - uses: actions/checkout@v2 # Github Action: checks out code in repository, allows you to run code
    - name: Run Django unit tests # just a description
      run: |
        pip3 install --user django
        python3 manage.py test
      # install django to test in Github
      # then run the usual 'python3 manage.py test' (run all tests in this app!) ['test' points to default-given 'tests.py' in app...]
# Will give back some response




# # # Set up workflow for Project:
  # Github.com > Create New Workflow

# # # Once you have a DJANGO APP Project and a tests.py file
  # git status
  # git add . # (once .yml file is created and ready)
  # git commit -m "some message..."

# # # Go to Github.com:
  # Issues: where people can report a bug/issue... (list of pending action items to deal with, then close)
  # Pull Requests: a queue for people to request merging their code into master-branch of Github repository (common practice: people can review code before it is merged into master branch, possibly 'rejecting' and suggesting updates before merging)
  # Actions:
